### ISSUE TITLE
404 FISH NOT FOUND

### ISSUE THREAD

**Issue by spijker** [EndMove/pufferpanel-adm#1]
After installation , opened the site URL 
got direct a  http://x.x.x.x:8080/errors/404
404 FISH NOT FOUND

docker logs -f PufferPanel
`[GIN] 2022/09/20 - 20:38:38 | 200 |     256.695µs |   x.x.x.x | GET      "/api/config"
[GIN] 2022/09/20 - 20:38:47 | 200 |     248.927µs |   x.x.x.x | GET      "/api/config"
[GIN] 2022/09/20 - 20:39:52 | 200 |     214.679µs |   x.x.x.x | GET      "/api/config"
[GIN] 2022/09/20 - 20:41:17 | 200 |     230.875µs |   x.x.x.x | GET      "/api/config"
`

removed the embedded database & restarted docker, still the same issue.

**Comment by EndMove** [comment]
Hello spijker,

Can you give me more information about the installation environment : Server model, ADM version, Docker version?  You can also send me the log file of the last launch (after uninstalling and reinstalling the application) ``~/Docker/PufferPanel/logs/***.log``.

The docker log you share with me below is normal, Puffer starts by loading its configuration on a panel access attempt.

Also check that the two ports pufferpanel uses are available by disabling the application and running this command: ``netstat -ltnp | grep -e 8080 -e 5657``. Indeed puffer pannel needs port `8080` for its web server and port `5957` for its daemon's SFTP server. If when you run this command netstat shows that the port is in use, you have found the problem. If not, please get back to me.

Sincerely,
EndMove.

**Comment by spijker** [comment]
adm : 4.1.0.RKM1
Docker version 20.10.17, build 100c701
Asustor : AS5202T

Removed the docker & reinstalled , same issue.
It's running correctly 

netstat -ltnp | grep -e 8080 -e 5657
tcp        0      0 :::8080                 :::*                    LISTEN      -
tcp        0      0 :::5657                 :::*                    LISTEN      -

Tha logs : 
https://pastebin.com/MgvkUYtv

After start , first time interface 
[GIN] 2022/09/26 - 12:04:07 | 200 |   77.514843ms |   192.168.1.172 | GET      "/js/app.c5dccc05.js"
[GIN] 2022/09/26 - 12:04:07 | 200 |   79.214229ms |   192.168.1.172 | GET      "/css/chunk-vendors.2aea4b8f.css"
[GIN] 2022/09/26 - 12:04:07 | 200 |  112.146283ms |   192.168.1.172 | GET      "/js/chunk-vendors.473f0a10.js"
[GIN] 2022/09/26 - 12:04:08 | 200 |     280.313µs |   192.168.1.172 | GET      "/api/config"
[GIN] 2022/09/26 - 12:04:08 | 200 |   41.521848ms |   192.168.1.172 | GET      "/fonts/materialdesignicons-webfont.7a44ea19.woff2"

**Comment by spijker** [comment]
please close this one, it's working now ;)
Cleared the cache etc etc , now i'm getting the login interface, think it was just that ;(
